version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data
        networks:
            - elknetwork
        restart: always
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
        restart: always
    # logstash:
    #     image: docker.elastic.co/logstash/logstash:7.10.0
    #     container_name: logstash
    #     hostname: logstash
    #     ports:
    #         - 9600:9600
    #         - 8089:8089
    #     volumes:
    #       - ${DATA_DIR}/logstash:/usr/share/logstash/pipeline/
    #     links:
    #         - elasticsearch:elasticsearch
    #     depends_on:
    #       - elasticsearch
    #     networks:
    #       - elknetwork
    # app:
    #     image: harisshafiq09/sample-app:latest
    #     container_name: app
    #     command: /var/sample-app
    #     ports:
    #         - 8083:8083
    #     logging:
    #         driver: syslog
    #         options:
    #             syslog-address: "tcp://localhost:8089"
    #     depends_on:
    #       - logstash
    #     networks:
    #       - elknetwork
networks:
    elknetwork:
        driver: bridge