FROM docker.elastic.co/kibana/kibana:7.10.0

LABEL maintainer="RSchop" \
      description="Kirbana Risc"

# COPY requirements.txt /
# RUN pip install -r /requirements.txt

COPY kibana.yml /usr/share/kibana/config/
# WORKDIR /app

# CMD ["python3", "-u", "things881130.py"]